sudo: required
language: generic

os:
  - linux
  - osx
script:
 - fish tests/run-omf.fish
 - fish tests/run-fisher.fish

install:
  # OSX
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update      ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install fish; fi

  # LINUX
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-add-repository -y ppa:fish-shell/release-2; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y fish; fi

jobs:
  include:
    - stage: deploy
      language: node_js
      node_js: stable
      if: branch = master AND type = push
      script: npm run docs:build
      deploy:
       provider: pages
       skip-cleanup: true
       github-token: $GITHUB_TOKEN
       keep-history: true
       local-dir: _book
