sudo: required
language: generic

os:
  - linux
  - osx
env:
 - TEST_COMMAND="HOME=/tmp/spacefish fish tests/run-omf.fish"
 - TEST_COMMAND="HOME=/tmp/spacefish fish tests/run-fisher.fish"

script: (eval "$TEST_COMMAND")

install:
  mkdir -p /tmp/spacefish
  # OSX
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install fish; fi

  # LINUX
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-add-repository -y ppa:fish-shell/release-2; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y fish                       ; fi

jobs:
  include:
    - stage: deploy
      language: node_js
      node_js: stable
      if: branch = master AND type = push
      script: npm run docs:build
      deploy:
       provider: pages
       skip-cleanup: true
       github-token: $GITHUB_TOKEN
       keep-history: true
       local-dir: _book
